export class ErrorCodes {
    public static ERROR_INVALID_REFRESH_TOKEN = 'ERROR_INVALID_REFRESH_TOKEN'
    public static ERROR_TOPIC_DOES_NOT_EXIST = "ERROR_TOPIC_DOES_NOT_EXIST";
    public static ERROR_USER_WITH_EMAIL_EXISTS = "ERROR_USER_WITH_EMAIL_EXISTS";
    public static ERROR_EMPTY_TOPIC = "ERROR_EMPTY_TOPIC";
    public static ERROR_USER_HAS_NO_STATISTICS = "ERROR_USER_HAS_NO_STATISTICS";
    public static ERROR_USER_DOES_NOT_EXIST = "ERROR_USER_DOES_NOT_EXIST";
    public static ERROR_INVALID_EMAIL_OR_PASSWORD = "ERROR_INVALID_EMAIL_OR_PASSWORD";
    public static ERROR_INVALID_EMAIL_FORMAT = "ERROR_INVALID_EMAIL_FORMAT";
    public static ERROR_MISSING_USER_ID = "ERROR_MISSING_USER_ID";
    public static ERROR_PARAMETERS_CANNOT_BE_EMPTY = "ERROR_PARAMETERS_CANNOT_BE_EMPTY";
    public static ERROR_INVALID_ACHIEVEMENT_ID = "ERROR_INVALID_ACHIEVEMENT_ID";
    public static ERROR_INVALID_LANGUAGE = "ERROR_INVALID_LANGUAGE";
    public static ERROR_INVALID_IMAGE_PATH = "ERROR_INVALID_IMAGE_PATH";
    public static ERROR_INVALID_IMAGE_EXTENSION = "ERROR_INVALID_IMAGE_EXTENSION";
    public static ERROR_INVALID_PAYLOAD = "ERROR_INVALID_PAYLOAD";
    public static ERROR_INVALID_COURSE = "ERROR_INVALID_COURSE";
    public static ERROR_INVALID_USER_ID_FORMAT = "ERROR_INVALID_USER_ID_FORMAT";
    public static ERROR_INVALID_WORD_ID = "ERROR_INVALID_WORD_ID";
    public static ERROR_USER_ALREADT_KNOW_THIS_WORD = "ERROR_USER_ALREADy_KNOW_THIS_WORD";
    public static ERROR_USER_SETTINGS_NOT_FOUND = "ERROR_USER_SETTINGS_NOT_FOUND";
    public static ERROR_THIS_USER_ALREADY_LEARNING_THIS_COURSE = 'ERROR_THIS_USER_ALREADY_LEARNING_THIS_COURSE'
    public static ERROR_COURSE_AND_INTERFACE_LANGUAGE_CANNOT_BE_THE_SAME = "ERROR_COURSE_AND_INTERFACE_LANGUAGE_CANNOT_BE_THE_SAME";
    public static ERROR_USER_DIDNT_CHOOSE_ANY_COURSE = 'ERROR_USER_DIDNT_CHOOSE_ANY_COURSE'
    public static ERROR_INVALID_JWT_TOKEN = 'ERROR_INVALID_JWT_TOKEN'
    public static ERROR_SKIPPED_RECOVER_STEPTS = 'ERROR_SKIPPED_RECOVER_STEPTS'
}